### ISSUE TITLE
Use an open license

### ISSUE THREAD

**Issue by abh** [boyter/lc#2]
It seems a little paradoxical to have a tool to help manage licenses itself be under a particularly incompatible/restrictive license. :-)

**Comment by boyter** [comment]
The choice of GPL3 was deliberate as I believe any modification should be shared with the user and with the community. Happy to hear discussions beyond that it is incompatible/restrictive though.

**Comment by boyter** [comment]
Since no response going to close it down. Happy for you to open again if you wish to discuss it.

**Comment by abh** [comment]
> On Feb 9, 2018, at 4:53, Ben Boyter <notifications@github.com> wrote:
> 
> The choice of GPL3 was deliberate as I believe any modification should be shared with the user and with the community. Happy to hear discussions beyond that it is incompatible/restrictive though.

Hi,

Obviously it’s your choice — just for a tool like this it really seemed like a curious choice. I am sure that my thoughts are colored by my particular experience and background, but all the same.

At my dayjob our group made a similar tool to keep track of licenses (and the appropriate reviews/approval process). We’re generally not allowed to contribute back to GPLv3 projects, so I didn’t look at your tool past seeing the license. From my perspective it seems likely that many potential users (and thus contributors) of your tool would be ones in a similar situation.

Google has a good overview of licenses from a corporate perspective: https://opensource.google.com/docs/thirdparty/licenses/#restricted


Ask

**Comment by boyter** [comment]
I guess I was just not comfortable the idea that someone could take what is presented here and package it up with modifications without them flowing back into the community, hence the choice. 

I can understand why some may not want to contribute back to it because of that but I think I am prepared to deal with it.

**Comment by boyter** [comment]
Thought it over. 

Now dual licensed MIT and UNLICENSE
