### ISSUE TITLE
Add macOS release

### ISSUE THREAD

**Issue by ojkelly** [boyter/lc#24]
Should be possible with Travis's macOS environment.
https://docs.travis-ci.com/user/reference/osx

**Comment by boyter** [comment]
Should probably hook it up to actually build the release files themselves actually.

**Comment by boyter** [comment]
BTW happy to get a pull request for this.

**Comment by boyter** [comment]
So the only way I can see to do this is have it upload to S3 at the end of the process. Not sure if I want to do that. Maybe if someone wants to provide builds? Its not too hard to compile from source thankfully...

**Comment by boyter** [comment]
So the only way I can see to do this is have it upload to S3 at the end of the process. Not sure if I want to do that. Maybe if someone wants to provide builds? Its not too hard to compile from source thankfully... 

It is verified that its building now so I may just close this down.

**Comment by boyter** [comment]
Done through cross compiling. See latest release for OSX binary https://github.com/boyter/lc/releases/tag/v1.2.2
