### ISSUE TITLE
Add topic: open-source-licensing

### ISSUE THREAD

**Issue by katrinleinweber** [boyter/lc#47]
Thanks for publishing this! I think it would be better findable, if displayed on [GitHub.com/topics/licensee](https://github.com/topics/open-source-licensing), please consider [adding that topic](https://help.github.com/articles/about-topics/) to this repo. Thank you :-)

**Comment by boyter** [comment]
Done.

**Comment by katrinleinweber** [comment]
Cool, thanks :-)
